export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const TOGGLE_CART_DROPDOWN = "TOGGLE_CART_DROPDOWN";
export const ADD_ITEM_TO_THE_CART = "ADD_ITEM_TO_THE_CART";
export const REMOVE_ITEM_FROM_THE_CART = "REMOVE_ITEM_FROM_THE_CART";
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";
